### PR TITLE
Pull

### PR DESCRIPTION
**Pull request by keithodulaigh**

### CODE REVIEW

**Comment by cmaeder** [comment]
this request looks reasonable wrt to EVT logic. However, a couple of unrelated (or generated) files are deleted or added. A description is missing. :-1:

**Comment by mariefarrell** [comment]
Sorry, never intended for it to go upstream. A work in progress.

**Comment by cmaeder** [comment]
no problem, you can simply add more commits until your branch is ready. (We just need to know that this PR is not ready yet for merging.)

**Comment by cmaeder** [comment]
But you can also close this PR and make a new and cleaner one later.

**Pull request closed without merging**
