### PR TITLE
simplify version checking in makefiles

### PR DESCRIPTION
**Pull request by jelmd**
Please test on non-Ubuntu platforms.

### CODE REVIEW

**Comment by eugenk** [comment]
Compiles just fine on macOS 10.13.2 without ksh93.

**Comment by eugenk** [comment]
On another note (since you are changing the Makefiles and): 
Are there any supported Ubuntus left that don't have a warp3 (but only a warp1) package?

**Comment by jelmd** [comment]
Wrt. warp1 + ubuntu. Not sure, but at least trusty. Anyway, doesn't really matter because one does not have to use the system packages ;-) .

**Comment by jelmd** [comment]
Wrt. MacOS: good - wasn't sure (my Mac is dead, accu bumped to 3x size). IIRC MacOSX (at least tiger .. *capitan) shipped with ksh93. Not anymore?

**Comment by eugenk** [comment]
macOS is shipped with the executable `ksh`:
```
❯ /bin/ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
```
but not with with an executable named`ksh93`.

It is, however, always shipped with `/bin/bash`.

**Comment by jelmd** [comment]
Ahh ok, thanx.

BTW: Just saw, that the commit already contains the GHC_PKG_FLAGS. So will add another change, which honors GHC_FLAGS, so that one may use some flags on-the-fly.

**Comment by jelmd** [comment]
Anything else?

**Comment by eugenk** [comment]
Still need to test this on arch linux. Will do this tomorrow.

**Comment by eugenk** [comment]
Compiles fine on Arch Linux, too.

> doesn't really matter because one does not have to use the system packages ;-)

Isn't this required in a PPA?

**Comment by jelmd** [comment]
PPA requirements: either system packages or packages from the PPA in use.
However, if one maintains its own "Haskell Platform" (e.g. because needs to avoid certification process for all "new modules" ...) it may contain, whatever is needed/sufficient for his primary projects.

**Pull request merged**
