### PR TITLE
update owlapi to 3.5.1, update FaCT++ to 1.6.3.1

### PR DESCRIPTION
**Pull request by ignazio1977**
This commit uses the precompiled owlapi binary available from Maven, which includes third party dependencies.
I have also updated FaCT++ to version 1.6.3.1 (Java and binary files)
I haven't done any more testing than just running make initalize_java, so it is possible that I might have missed something.

### CODE REVIEW

**Comment by ignazio1977** [comment]
Once 3.5.2 is released, it will be easy to update - just amend the version number.

**Comment by cmaeder** [comment]
Thanks for your help! I've continued your branch on the local branch https://github.com/spechub/Hets/tree/ignazio1977-master. Directly merging to master is not possible, because "hets -update" would not fit together with our old owlapi and the old libFaCTPlusPlusJNI.so installed by our libfactplusplus Ubuntu package from https://launchpad.net/~hets/+archive/ubuntu/hets. So I need to make new Ubuntu packages, first.

Currently calling fact++ or the OWLParser leads to:

```
./hets -g -i owl OWL2/tests/wine.rdf
*** Error:
process stop! ExitFailure 1
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/cache/CacheLoader
	at org.semanticweb.owlapi.vocab.OWLFacet.<init>(OWLFacet.java:87)
	at org.semanticweb.owlapi.vocab.OWLFacet.<clinit>(OWLFacet.java:60)
	at org.semanticweb.owlapi.vocab.OWL2Datatype$Category.<clinit>(OWL2Datatype.java:328)
	at org.semanticweb.owlapi.vocab.OWL2Datatype.<clinit>(OWL2Datatype.java:74)
	at uk.ac.manchester.cs.owl.owlapi.InternalsNoCache.<clinit>(InternalsNoCache.java:59)
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.<init>(OWLDataFactoryImpl.java:128)
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.<clinit>(OWLDataFactoryImpl.java:74)
	at org.semanticweb.owlapi.apibinding.OWLManager.getOWLDataFactory(OWLManager.java:152)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:113)
	at OWL2Parser.setupManagerWithMissingImportListener(OWL2Parser.java:187)
	at OWL2Parser.<clinit>(OWL2Parser.java:44)
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheLoader
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 11 more
```

**Comment by cmaeder** [comment]
your chances went into #1479

**Comment by cmaeder** [comment]
Thanks again.

**Comment by ignazio1977** [comment]
No problem, glad I could help.

**Pull request closed without merging**
