### PR TITLE
better error message for Logic.Logic.inclusion

### PR DESCRIPTION
**Pull request by tillmo**
the error message informs about the context that an inclusion is being constructed, and also prints source and target signature

### CODE REVIEW

**Comment by tillmo** [comment]
@eugenk, do you understand the error message at https://travis-ci.org/spechub/Hets/jobs/273800782 ?

**Comment by tillmo** [comment]
hm, now both checks fail...

**Comment by mcodescu** [comment]
This is strange, the modifications look completely fine to me.

**Comment by eugenk** [comment]
Travis CI sets this environment variable, which breaks the test suite. Both checks failed because I made a mistake in the `.travis.yml`. This is fixed my last commit (by `--amend`).

I have no idea why this the error came with this pull request because I can see no change that might have introduced this problem. Perhaps Travis changed things on their end.

**Comment by jelmd** [comment]
Such a change would make sense, probably because lot of test envs do not set it by its own and thus wasting huge amounts of RAM/causing memory pressure without actually needing that much. IIRC, per default the JVM grows "its mem pool" 'til max., before it tries a little bit harder to garbage collect and re-use portions of the mem-pool. And IIRC., at least for Sun/Oracle JDKs the max. mem default is 4GB (I guess, for OpenJDK it is the same or more) ...

**Comment by tillmo** [comment]
OK, now everything is fine. @mcodescu, can you please have a look?

**Comment by mcodescu** [comment]
:+1:

**Pull request merged**
