### PR TITLE
1742 extend owl syntax to swrl rules

### PR DESCRIPTION
**Pull request by b-gehrke**
Abstract / Functional Syntax according to https://www.cs.ox.ac.uk/files/2445/rulesyntaxTR.pdf implemented.

### CODE REVIEW

**Review by mcodescu — COMMENTED** [review]
It looks fine, I haven't tested the code yet. I'll do this once the matter with parsing data/object properties is fixed.

**Comment by b-gehrke** [comment]
@mcodescu Have you had a chance to look at it yet? The unknown types have been added. In the implemented FS Parser they are not used as in FS they can be uniquely identified.

**Review by mcodescu — APPROVED** [review]
:+1: 
Looks fine. Should I merge this?

**Comment by jelmd** [comment]
@b-gehrke To trigger a travis CI check, adding a dummy commit (e.g. add or rm an empty line somewhere) should work.

**Comment by b-gehrke** [comment]
@jelmd It doesn't seem like the CI checks run.

@mcodescu I think we can skip the checks once more for this PR. So yes, please merge it.

**Comment by jelmd** [comment]
@b-gehrke strange. Maybe travis-ci changed its behavior wrt. to branch:only a little bit. Dropped it in .travis.yml  - hopefully it doesn't break other stuff ...

**Pull request merged**
