### PR TITLE
Add a hint to skip installation of provers on macOS to the Readme.

### PR DESCRIPTION
**Pull request by eugenk**

### CODE REVIEW

**Comment by tillmo** [comment]
hm, I cannot really test your instructions. Who could we ask to do this?

**Comment by eugenk** [comment]
Fabian uses a mac. He actually used this to install Hets quite a while ago (because one of the optional dependencies did not compile). He asked me to put this information on hets.eu, but I took quite a lot of time to do this.

**Comment by tillmo** [comment]
@fabianneuhaus, could you please have a look?

**Comment by eugenk** [comment]
Are there any news on the review? Do I need to change things?

**Comment by eugenk** [comment]
Fixed it with 6bc0ad310

**Pull request merged**
