### PR TITLE
Iris

### PR DESCRIPTION
**Pull request by mcodescu**
fixes for #1880, #1882.

### CODE REVIEW

**Comment by mcodescu** [comment]
I can't reproduce the error of the test on my machine:
```
./hets --quiet -a none  ~/repos/Hets-lib/Ontology/Examples/OpenAALOntology.owl 
mcodescu@dell:~/repos/Hets2$ 
```
and calling Hets with `-g` gives the expected result.

**Comment by mcodescu** [comment]
The IRI `http://www.w3.org/2001/XMLSchema#string` is not stored in the expected way: 
```
scheme:http:
no authority
path://www.w3.org/2001/XMLSchema#string
query:
fragment:
prefix:
isAbbrev:False
```
The prefix should be `http`, not empty, and the scheme should be empty. I'll try to fix this.

**Comment by mcodescu** [comment]
In `OWL2/AS.hs/checkPredefAux` the `prefixName` of an IRI is compared with `http`. Now, I have changed this to `iriScheme` and compared with `http:` (First issue, the colon should not be saved here, or the assumption that it is saved should be made everywhere in the code). With this change, `http://www.w3.org/2001/XMLSchema#string` is recognized as a datatype. But `xsd:boolean` is no longer recognized. The method has to take both cases into account. As a hack in the last commit, I used the `iriScheme` if it's non-empty, otherwise the `prefixName` is used. With this hack, things work. Another bug is revealed: `xsd:boolean` is displayed `xsdboolean`. It looks to me that `Common/IRI.hs/iriToStringAbbrev` should add separators instead of assuming they are stored.

**Comment by mcodescu** [comment]
#1858 also works as expected on this branch

**Review by tillmo — APPROVED** [review]
looks good and solves the issues, but please wait for travis (I have merged in master).

**Comment by mcodescu** [comment]
Travis failes but this seems not to be related to the changes.

**Comment by tillmo** [comment]
It seems that travis just has a timeout. I try again with #1943

**Comment by tillmo** [comment]
The travis problem is this:
```
[163 of 839] Compiling OWL2.Parse       ( OWL2/Parse.hs, OWL2/Parse.o )
OWL2/Parse.hs:24:1: warning: [-Wunused-imports]
    The import of ‘Common.Id’ is redundant
      except perhaps to import instances from ‘Common.Id’
    To import instances alone, use: import Common.Id()
OWL2/Parse.hs:29:1: warning: [-Wunused-imports]
    The import of ‘sortId’ from module ‘Common.Token’ is redundant
Current RSS of 11379: 5.4G
Ooops, that's too much.
[164 of 839] Compiling OWL2.ManchesterParser ( OWL2/ManchesterParser.hs, OWL2/ManchesterParser.o )
make[1]: *** [hets_server-opt] Error 1
Makefile:510: recipe for target 'hets_server-opt' failed
make: *** [hets_server.bin] Terminated
Makefile:907: recipe for target 'hets_server.bin' failed
```
Actually, this failure does not make the test fail, because hets_server-opt is built successfully afterwards. However, this second attempt causes a longer running time that then causes the failure. The question is how to avoid this first failure.

**Comment by tillmo** [comment]
The crucial lines are:
```
Current RSS of 11379: 5.4G
Ooops, that's too much.
```
But why does the memory consumption increase so much?

**Comment by mcodescu** [comment]
After a restart, I don't get a timeout anymore. This is strange.

**Pull request merged**
