### PR TITLE
add CI job for docker publishing

### PR DESCRIPTION
**Pull request by daniilsvc**

### CODE REVIEW

**Comment by jelmd** [comment]
We do not use travis CI anymore because of unreliability.

**Comment by daniilsvc** [comment]
@jelmd , sorry but I don't understand how travis relates to it. If I open `Actions` tab I can see list of workflows already run and link to  the file `.Hets/.github/worflows/ci.yml`. I assume we use github actions and don't see where travis comes into play.

Checks here stuck (as I understand) because of access to encrypted secrets incorrect (there is no such variables). Or because of branch protection rules. But I don't access to 'secrets' and can't uncheck smth like `Require status checks to pass before merging`.

So, correct me if I wrong:
1) Hets/.github/workflows/ci.yml does nothing about travis
2) We don't have secrets fields like DOCKER_HUB_USERNAME, DOCKER_HUB_ACCESS_TOKEN

**Comment by jelmd** [comment]
> @jelmd , sorry but I don't understand how travis relates to it.

Me either ;-). Eventually I was working on another task and put the reply into the wrong widget ...

> If I open `Actions` tab I can see list of workflows already run and link to the file `.Hets/.github/worflows/ci.yml`. I assume we use github actions and don't see where travis comes into play.

Yepp. Travis-CI has been dropped here as well.

> Checks here stuck (as I understand) because of access to encrypted secrets incorrect (there is no such variables). Or because of branch protection rules. But I don't have access to 'secrets' and can't uncheck smth like `Require status checks to pass before merging`.
> 
> So please correct me if I wrong:
> 
>     1. Hets/.github/workflows/ci.yml does nothing about travis

Yepp, just GHA.

>     2. We don't have secrets fields like DOCKER_HUB_USERNAME, DOCKER_HUB_ACCESS_TOKEN

You mean variables in `Repository secrets` named like this? No, there are no such vars.

**Comment by tillmo** [comment]
since @daniilsvc has left, @jelmd can you please take care of this issue?

**Review by b-gehrke — APPROVED** [review]
:+1:

**Pull request merged**
