### PR TITLE
changed analysis of string such that type of imported files in libraries can be guessed

### PR DESCRIPTION
**Pull request by mcodescu**
If a string is a file name, we should be able to guess its type and parse it with the appropriate tool.

### CODE REVIEW

**Comment by cmaeder** [comment]
```
Static/AnalysisLibrary.hs:136:57: trailing (1) white space
Static/AnalysisLibrary.hs:137:27: put blank before {
Static/AnalysisLibrary.hs:139:14: put blank after <-
```

**Comment by mcodescu** [comment]
Christian, thanks for your change! Does this mean that we can now merge this pull request?

**Comment by cmaeder** [comment]
This change simply ignores the `-i` setting of the command line. `readLibDefn` is called for the top-level library and imported libraries. 

I don't know how to check for the top-level or imports (maybe by looking into `LNS`).

**Comment by cmaeder** [comment]
forget this PR and use https://github.com/spechub/Hets/pull/1534

**Pull request closed without merging**
