### PR TITLE
1966 revert gtk3

### PR DESCRIPTION
**Pull request by tillmo**
This will temporarily revert @TpmKranz's commits 902b472..f4ac445.
The reason is that Janna wants to make experiments and needs a packaged version, but currently, packaging does not work due to #1966.
Later, we should restore @TpmKranz's commits and simultaneously properly solve #1966.

### CODE REVIEW

**Comment by jelmd** [comment]
Not sure, what problem stack has wrt. jenkins, but on bionic normal build fails with:
```
GUI/GtkUtils.hs:549:3: error:
    * No instance for (TreeModelClass (Maybe (ListStore a)))
        arising from a use of `treeViewSetModel'
    * In a stmt of a 'do' block: treeViewSetModel view (Just store)
      In the expression:
        do { store <- listStoreNew listData;
             treeViewSetModel view (Just store);
             treeViewSetHeadersVisible view False;
             ren <- cellRendererTextNew;
             .... }
      In an equation for `setListData':
          setListData view getT listData
            = do { store <- listStoreNew listData;
                   treeViewSetModel view (Just store);
                   treeViewSetHeadersVisible view False;
                   .... }
make[1]: *** [hets-opt] Error 1
make: *** [hets.bin] Error 2
```
I guess not everything got caught on revert.

**Comment by tillmo** [comment]
This is strange, because I have reverted all commits by @TpmKranz

**Comment by jelmd** [comment]
Well, the build pulled v0.105 - the master. This branch compiles on our build machine, so bionic packages are at least available via https://pkg.cs.ovgu.de/LNF/linux/ubuntu/18.04/. Make sure to choose 0.105.0!

launchpad: trying to convince it to build for bionic (don't care if xenial fails). Not sure what problem it has - maybe something like on xenial, the OOM killer nukes it or not enough space ... For focal I do not try because the libghc-glade-dev_0.13.1 fails to build but is required by hets. Perhaps Christian can take care of it.

**Comment by tillmo** [comment]
I see. This is just a PR, i.e. a branch, and neither master nor a release. Do I have to make a release first?

**Comment by jelmd** [comment]
No extra release needed. Bundled the PR as patch (https://github.com/spechub/Hets/pull/1975.patch) with release 0.105, modified it a little bit, so that the diff on lunch pack eats it and viola :). xenial and bionic packages are available now.

**Comment by tillmo** [comment]
great!

**Comment by jelmd** [comment]
Since not needed anymore (and gtk3 is a little bit misleading anyway) it should be closed w/o merging it?

**Comment by tillmo** [comment]
> Since not needed anymore (and gtk3 is a little bit misleading anyway) it should be closed w/o merging it?

yes

**Pull request closed without merging**
