### PR TITLE
Owl datatypes in casl

### PR DESCRIPTION
**Pull request by mcodescu**
Not sure that this is optimal, please have a look. I have split the predefined theory in smaller parts corresponding to each type, stored the parts in a map according to the name of the sort, and unite all parts corresponding to the datatypes in the sublogic of a theory.

### CODE REVIEW

**Comment by tillmo** [comment]
looks good in general!
I have found some problem. Try `hets -g https://ontohub.org/bioportal/BIM.owl`, translate the ontology to CASL, save the result to a file, and analyse this again with hets. Then I get:
```
/home/till/bin/hets  -g  /home/till/temp/BIM.owl.het
### file name '/home/till/temp/BIM.owl.het' does not match library name 'BIMowl'
Analyzing file /home/till/temp/BIM.owl.het as library BIMowl
logic CASL.SulFOL=
Analyzing spec BIMowl?Spec
/home/till/temp/BIM.owl.het:720.54: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:719.49: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:718.44: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:717.39: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:716.34: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:715.29: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:714.24: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:713.19: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:712.14: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:711.9: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:757.49: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:756.44: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:755.39: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:754.34: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:753.29: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:752.24: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:751.19: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:750.14: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:749.9: *** Error:
unexpected mixfix token: :@:
/home/till/temp/BIM.owl.het:821.32-821.36: *** Error:
no matching qualified variable found 'gn_x2'
/home/till/temp/BIM.owl.het:822.36-822.40: *** Error:
no matching qualified variable found 'gn_x2'
/home/till/temp/BIM.owl.het:825.27-825.31: *** Error:
no matching qualified variable found 'gn_x2'
/home/till/temp/BIM.owl.het:826.31-826.35: *** Error:
no matching qualified variable found 'gn_x2'
/home/till/temp/BIM.owl.het:829.32-829.36: *** Error:
no matching qualified variable found 'gn_x2'
/home/till/temp/BIM.owl.het:830.36-830.40: *** Error:
no matching qualified variable found 'gn_x2'
/home/till/temp/BIM.owl.het:833.32-833.36: *** Error:
no matching qualified variable found 'gn_x2'
/home/till/temp/BIM.owl.het:834.32-834.36: *** Error:
no matching qualified variable found 'gn_x2'
/home/till/temp/BIM.owl.het:837.30-837.34: *** Error:
no matching qualified variable found 'gn_x2'
hets: user error (Stopped due to errors)
```

**Comment by mcodescu** [comment]
Well I misplaced the cons in the reals signature, corrected now. Still have to see about the variables.

**Comment by mcodescu** [comment]
The second error is caused by a bug in translation of equivalent data properties, I'm fixing that now.

**Comment by mcodescu** [comment]
Now I can read in Hets the translation of BIM to CASL.

**Comment by tillmo** [comment]
:+1: modulo travis. Later on, we should do more tests with the Bioportal ontologies.

**Pull request merged**
