### PR TITLE
Ghc 7.10

### PR DESCRIPTION
**Pull request by cmaeder**
The following changes should be added to ease transition to ghc-7.10. They should not harm for older ghc versions. I've run a test using ghc-7.10RC2, but hexpat, wai-extra, warp und gtk stuff were still missing.

### CODE REVIEW

**Comment by eugenk** [comment]
You seem to have missed one instance in https://github.com/spechub/Hets/blob/ghc-7.10/Common/Lib/Maybe.hs#L23
```
[ 10 of 753] Compiling Common.Lib.Maybe ( Common/Lib/Maybe.hs, Common/Lib/Maybe.o )

Common/Lib/Maybe.hs:23:10: Warning:
    ‘MaybeT’ is an instance of Monad but not Applicative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
```

**Comment by cmaeder** [comment]
Right, the files  HolLight/HolLight2DG.hs and Common/SAX.hs that use Common/Lib/Maybe.hs have not yet been compiled with ghc-7.10-RC2 because hexpat was not available (and is "ifdef"-ed in hets.hs)

**Comment by eugenk** [comment]
Alright, so this shall be done in another branch? In that case: :+1:

**Comment by cmaeder** [comment]
no, I'll check hexpat this week.

**Comment by eugenk** [comment]
:+1:

**Pull request merged**
