### PR TITLE
1905 lossy translation

### PR DESCRIPTION
**Pull request by tillmo**
solves #1905 by providing a lossy flag `-Y` that makes translations to just leave out untranslatable axioms.
Note that #1706 must be solved before this one can be merged - otherwise, the proof support for CASL theories with sort generation constraints will be gone.

### CODE REVIEW

**Comment by tillmo** [comment]
OK, I have managed to introduce some logic that avoids the problem with proving. However, still there is some problem when trying it out. Do you have an idea way?

**Comment by mcodescu** [comment]
Could you please tell me what problem do you get, and perhaps also provide me the test file?

**Comment by tillmo** [comment]
I just have found and fixed the problem. Could you please review again (this time you can give an official OK...), including trying some proofs for CASL theories?

**Comment by mcodescu** [comment]
Now I get `ax_ax3` as the name of `ax3` in my test, or 'ax_ga_assoc___*__' for List.casl, and the behavior wrt. proving did not change. I think we can live with these names, but if we made somewhere (e.g. Ontohub or rest.hets.eu) the assumptions that comorphisms preserve names of sentences, we should be aware that this is no longer the case.
:+1:

**Comment by tillmo** [comment]
I needed to add `ax_` because axiom names starting with a digit like `1_def_Nat` are a syntax error in TPTP. We could restrict these additions to those axiom names starting with a digit, at the risk that the mapping is no longer injective (`0` and `ax_0` will be both mapped to `ax_0`). What do you think?

**Comment by mcodescu** [comment]
If a name `N` is not valid because it starts with a digit, we could check whether a sentence named `ax_N` is already part of the theory. If this is the case, we could generate a new name for the translation of `ax_N`.

**Comment by tillmo** [comment]
yes, but in case that theories are united after translation (e.g. if a whole development graph is translated along a comorphism, which the old Hets GUI offers via the menus), there still could be clashes. So perhaps we should stay with the easy name transformation, which also has the advantage that its inverse can be computed easily.

**Comment by mcodescu** [comment]
Fine with me, it's just names of sentences and we can still easily deduce their original name.

**Pull request merged**
