### PR TITLE
fixed #1546 for SoftFOL

### LINKED ISSUE #1546: TPTP/THF: No Symbols in Axioms/Theorems
Hets does not output any Symbols in the Axioms and Theorems for TPTP and THF:

##### TPTP (bad output)
```
$ hets -o xml --full-signatures -a none -v2 -O /tmp/ +RTS -K1G -RTS --full-theories -A https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/compts_1__t10_compts_1.p --input-type=tptp
$ cat /tmp/compts_1__t10_compts_1.p.xml
<?xml version='1.0' ?>
<DGraph filename="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/compts_1__t10_compts_1.p" mime-type="text/plain" libname="compts_1__t10_compts_1" dgnodes="1" dgedges="0" nextlinkid="0">
  <DGNode name="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/compts_1__t10_compts_1.p" reference="false" logic="SoftFOL" refname="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/compts_1__t10_compts_1.p" relxpath="/">
    <Declarations>
      <Symbol kind="sort" name="U" iri="U">U</Symbol>
      [...]
      <Symbol kind="predicate" name="v2_compts_1" iri="v2_compts_1">v2_compts_1: U * U</Symbol>
    </Declarations>
    <Symbols>
      <Symbol kind="sort" name="U" iri="U">U</Symbol>
      [...]
      <Symbol kind="predicate" name="v2_compts_1" iri="v2_compts_1">v2_compts_1: U * U</Symbol>
    </Symbols>
    <Axioms>
      <Axiom name="antisymmetry_r2_hidden">
        <Text>[...]</Text>
        <AST>[...]</AST>
### Symbols should be here ###
      </Axiom>
      [...]
    </Axioms>
    <Theorems>
      <Theorem status="open" name="t10_compts_1">
        <Text>[...]</Text>
        <AST>[...]</AST>
### Symbols should be here ###
      </Theorem>
    </Theorems>
  </DGNode>
</DGraph>
```

##### THF (bad output)
```
$ hets -o xml --full-signatures -a none -v2 -O /tmp/ +RTS -K1G -RTS --full-theories -A https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/ALG294-5.het
$ cat /tmp/ALG294-5.xml
<?xml version='1.0' ?>
<DGraph filename="https://gist.githubusercontent.com/eugenk/1e4dcbc0106e5120bb06/raw/8f9ea2860eee9006940ae17bc42c63781c8edc69/ALG294-5.het" mime-type="text/het" libname="ALG2945" dgnodes="1" dgedges="0" nextlinkid="0">
  <DGNode name="ALG2945" range="https://gist.githubusercontent.com/eugenk/1e4dcbc0106e5120bb06/raw/8f9ea2860eee9006940ae17bc42c63781c8edc69/ALG294-5.het:3.1-3.14" reference="false" logic="THF" refname="ALG2945" relxpath="/">
    <Theorems>
      <Theorem status="open" name="cPU_X2310B_pme" range="https://gist.githubusercontent.com/eugenk/1e4dcbc0106e5120bb06/raw/8f9ea2860eee9006940ae17bc42c63781c8edc69/ALG294-5.het:58.13-192.22">
        <Text>[...]</Text>
        <AST>[...]</AST>
### Symbols should be here ###
      </Theorem>
    </Theorems>
  </DGNode>
</DGraph>
```

##### CASL (good output)
```
$ hets -o xml --full-signatures -a none -v2 -O /tmp/ +RTS -K1G -RTS --full-theories -A https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl
$ cat /tmp/Subclass.xml
<?xml version='1.0' ?>
<DGraph filename="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl" mime-type="text/het" libname="Subclass" dgnodes="3" dgedges="2" nextlinkid="2">
  <DGNode name="Subclass" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:1.1-19.3" reference="false" logic="CASL" refname="Subclass" relxpath="/">
    <Declarations>
      <Symbol kind="sort" name="s" iri="s" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:2.8">sort s</Symbol>
      [...]
    </Declarations>
    <Symbols>
      <Symbol kind="sort" name="s" iri="s" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:2.8">sort s</Symbol>
      [...]
    </Symbols>
    <Axioms>
      <Axiom name="transitivity" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:11.20-13.72">
        <Text>[...]</Text>
### Symbols are here: ###
        <Symbol kind="sort" name="s" iri="s" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:13.18">sort s</Symbol>
        <Symbol kind="pred" name="subclass" iri="subclass" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:13.22-13.29">pred subclass : s * s</Symbol>
        <AST>[...]</AST>
      </Axiom>
      [...]
    </Axioms>
  </DGNode>
  [...]
</DGraph>
```

### PR DESCRIPTION
**Pull request by tillmo**

### CODE REVIEW

**Comment by tillmo** [comment]
hm, the test failures seem not be related with this pull request

**Comment by eugenk** [comment]
No, they are not related. They fail on master as well. It seems like a dependency issue (but no dependencies have been changed since the last successful test).

**Comment by tillmo** [comment]
anyway, we can sort this out later, and you can go ahead with your evaluation based on this branch.

**Comment by eugenk** [comment]
This works perfectly, also with Ontohub. Many thanks! :+1:

**Comment by tillmo** [comment]
OK, this time my local run of the tests must suffice.

**Comment by cmaeder** [comment]
compilation using another .travis.yml file succeeds in branch https://github.com/spechub/Hets/tree/precise_orig_test

**Pull request merged**
