### PR TITLE
make hets compatible with ghc 8.8.4 and lts-16.31

### PR DESCRIPTION
**Pull request by daniilsvc**
This code compatible with both ghc 8.6.5 and ghc 8.8.4 (if we compile without stack), and also with both lts-14.27 and lts-16.31 (if we compile with stack). Related to #2064.

### CODE REVIEW

**Comment by daniilsvc** [comment]
If on master branch I run
`./hets test/IsabelleCoding/IsabelleCoding.dol -v5` 

I got next result:
```
Options:  --verbose=5 --encoding=utf8 --casl-amalg=cell test/IsabelleCoding/IsabelleCoding.dol
Processing input: test/IsabelleCoding/IsabelleCoding.dol
### Hint: mime-encoding: us-ascii
### Warning: set HETS_MAGIC to a proper magic file
### Hint:
a612499fd05e93ed675ad5ccfb6b4e7c219c3dbe76f2f603a6a9d45727486dd4  test/IsabelleCoding/IsabelleCoding.dol
Reading file file:///home/daniil/Documents/progs/Hets/test/IsabelleCoding/IsabelleCoding.dol
Analyzing library IsabelleCoding
Analyzing spec Options
Analyzing spec OptionsModel
file:///home/daniil/Documents/progs/Hets/test/IsabelleCoding/IsabelleCoding.dol:8.14-8.32:
### Hint:
derived symbol map:
{sort s |-> sort A}
Analyzing spec OptionsModel2
file:///home/daniil/Documents/progs/Hets/test/IsabelleCoding/IsabelleCoding.dol:15.14-15.35:
### Hint:
derived symbol map:
{sort s |-> sort Sing}
Current OutDir: /home/daniil/Documents/progs/Hets/test/IsabelleCoding/
```

As we can see - no error. But if I add traces to `Common.Result:resultToMonad`
```haskell
resultToMonad :: Monad m => String -> Result a -> m a
resultToMonad pos r = let ds = diags r in
  case (hasErrors ds, maybeResult r) of
    (False, Just x) -> return x
    _ -> trace "-- resultToMonad fail" $ fail $ pos ++ ' ' : showRelDiags 2 ds
```

I got the next response from hets:
```
Options:  --verbose=5 --encoding=utf8 --casl-amalg=cell test/IsabelleCoding/IsabelleCoding.dol
Processing input: test/IsabelleCoding/IsabelleCoding.dol
### Hint: mime-encoding: us-ascii
### Warning: set HETS_MAGIC to a proper magic file
### Hint:
a612499fd05e93ed675ad5ccfb6b4e7c219c3dbe76f2f603a6a9d45727486dd4  test/IsabelleCoding/IsabelleCoding.dol
Reading file file:///home/daniil/Documents/progs/Hets/test/IsabelleCoding/IsabelleCoding.dol
Analyzing library IsabelleCoding
Analyzing spec Options
Analyzing spec OptionsModel
-- resultToMonad fail
file:///home/daniil/Documents/progs/Hets/test/IsabelleCoding/IsabelleCoding.dol:8.14-8.32:
### Hint:
derived symbol map:
{sort s |-> sort A}
Analyzing spec OptionsModel2
-- resultToMonad fail
file:///home/daniil/Documents/progs/Hets/test/IsabelleCoding/IsabelleCoding.dol:15.14-15.35:
### Hint:
derived symbol map:
{sort s |-> sort Sing}
Current OutDir: /home/daniil/Documents/progs/Hets/test/IsabelleCoding/
```
We see that in `resultToMonad` function `fail` is called twice. I suppose section `Hint` in response describes errors in test file. But no actual errors raised from running Hets. Is this situation OK?

At this branch I have to change `resultToMonad`'s signature to directly face `MonadFail`
```haskell
resultToMonad :: Fail.MonadFail m => String -> Result a -> m a
```
But than I have a problem with function `propagateErrors`:
```No instance of (MonadFail Identity) ```
To work around that problem I simply substituted `fail` with `error` in `resultToMonad`. But `error` immediately stops execution with error message. That's why tests at this branch can't pass.

@tillmo do tests need to be revised? Is it OK to keep `error` function in `resultToMonad` instead of `fail` or current Hets behavior at master branch is normal and I should find another solution for ```No instance of (MonadFail Identity) ```?

**Comment by tillmo** [comment]
@jelmd could you please fix the dependency problem above. The constraint `ghc (< 8.8.2)` should be removed.

**Comment by jelmd** [comment]
> @jelmd could you please fix the dependency problem above. The constraint `ghc (< 8.8.2)` should be removed.

Well, this is a little bit tricky, because [debian's?] ghc puts all modules in versioned directories (e.g. `/usr/lib/haskell-packages/ghc/lib/x86_64-linux-ghc-8.6.5/aterm-0.1.0.2`). ghc v8.8.1 uses `/usr/lib/haskell-packages/ghc/lib/x86_64-linux-ghc-8.6.5/` as well, therefore a versioned constrain should be used to make clear, which version one needs to use to have all modules "in sync".

For jammy this probably needs to be adjusted. But right now I've no test/build system for jammy to check. @daniilsvc perhaps you can check?
```
dpkg -l ghc
ghc --version
# optional, install compiled in a test dir, e.g.
mkdir /tmp/test
runhaskell Setup.hs copy --destdir=/tmp/test/usr
find /tmp/test/usr| sort

```

**Comment by daniilsvc** [comment]
`dpkg -l ghc`
```Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-======================================
ii  ghc            8.8.4-3      amd64        The Glasgow Haskell Compilation system
```

`ghc --version`
```
The Glorious Glasgow Haskell Compilation System, version 8.8.4
```

**Comment by daniilsvc** [comment]
Path to packages:
`/usr/lib/haskell-packages/ghc/lib/x86_64-linux-ghc-8.8.4/`

**Comment by tillmo** [comment]
@jelmd plase check

**Comment by daniilsvc** [comment]
Hets compiled without stacks successfully on Jammy Ubuntu. This branch is ready to merge. @mcodescu review required.

**Review by mcodescu — APPROVED** [review]

**Pull request merged**
