### PR TITLE
1564 improve analysis of alignments

### PR DESCRIPTION
**Pull request by mcodescu**

### CODE REVIEW

**Comment by tillmo** [comment]
Previously,
```
logic OWL

ontology Woman = Class: Woman 
ontology Person = Class: Person
alignment Alignment1 : Woman to Person =
  Woman < Person
end

ontology AlignedOntology1 =
  combine Alignment1
end
```
in the colimit lead to
```
Class: Person
Class: Woman
       SubClassOf: Person
```
Now we get
```
Class: Person_target
Class: Woman_source
       SubClassOf: Person_target
```
I recall that you have told me why this is so, but still I want to discuss if there is a way to get the old version, which looks nicer.

**Comment by mcodescu** [comment]
I think we would need to test whether a symbol name that appears on the left side in a correspondence also appears on the right side. If this is the case, we must disambiguate. If that is not the case, we can keep the original names.

**Comment by tillmo** [comment]
good idea

**Comment by tillmo** [comment]
remaning issue relegated to #1597, hence :+1:

**Pull request merged**
