### PR TITLE
1945 owl functional syntax

### LINKED ISSUE #1945: OWL functional syntax
Switch to OWL functional syntax as the main abstract syntax for OWL2:

- define new datatypes for the abstract syntax based on OWL functional syntax, see https://www.w3.org/TR/owl2-syntax/
- provide a printer (maybe even through `deriving`)
- connect the abstract syntax to the OWL2 API
- write a Parsec parser for the functional syntax
- refactor the existing code (that is based on the Manchester syntax-based abstract syntax) to the new abstract syntax (this consists of many sub-steps)

### PR DESCRIPTION
**Pull request by b-gehrke**
Closes #1945 
OWL2 Functional Syntax implemented and set as default replacing Manchester Syntax as default AS.

### CODE REVIEW

**Comment by mcodescu** [comment]
We have some issues with performance.

On the master branch:
```
 Mon Nov 22 09:25 2021 Time and Allocation Profiling Report  (Final)

           hets +RTS -M10G -p -RTS -v2 -t OWL22CASL -o th chebi-no-annotations.owl

        total time  =      252.12 secs   (252122 ticks @ 1000 us, 1 processor)
        total alloc = 172,830,397,048 bytes  (excludes profiling overheads)

```
The same command on this branch is still running after more than one hour:
```
18522 mcodescu  20   0  1,001t 0,010t 143024 R 100,0 67,8  66:52.56 hets   
```

**Comment by mcodescu** [comment]
Without translating to CASL I get a result, but in longer time than on master with translation:
```
Mon Nov 22 11:33 2021 Time and Allocation Profiling Report  (Final)

           hets +RTS -M10G -p -RTS -v2 -o th chebi-no-annotations.owl

        total time  =      304.96 secs   (304965 ticks @ 1000 us, 1 processor)
        total alloc = 326,404,842,504 bytes  (excludes profiling overheads)

```

**Comment by b-gehrke** [comment]
I tested with the `HOIP.owl` ontology from bioportal. With the pushed changes (avoiding calls to `AS.changePrefixMapTypeToGA`) I was able to archive a speedup of ~1.3. Which is still ~52% slower than on master. One major reason seems to be the parsing of IRIs. On master it was done manually in `OWL2.XML` whereas we now rely on the parsers in `Common.IRI`.

I also tried to incorporate parallelization: Using parallel conversion with 12 threads from XML to AS I was able to archive a speedup of ~4.4 in comparison with this branch and ~2.3 in comparison to master. This would require the `parallel` package as a new dependency and to start hets with multiple threads using `+RTS -N<num threads>`

**Comment by mcodescu** [comment]
There are a few easy to solve warnings in OWL2.Extract. Otherwise we're good to merge.

**Comment by b-gehrke** [comment]
Warnings fixed

**Review by mcodescu — APPROVED** [review]
:+1:

**Comment by b-gehrke** [comment]
Travis doesn't report a status. Hence I cannot merge the PR. @mcodescu @tillmo Do you know what causes this?

**Comment by mcodescu** [comment]
I don't know but I could merge as admin if needed.

**Comment by tillmo** [comment]
The travis build has shown some error, see https://app.travis-ci.com/github/spechub/Hets/jobs/540365637  I do not know why this is not displayed here.

**Comment by mcodescu** [comment]
The error is:
```
OWL2/AS.hs:982:3: error: parse error on input ‘|’

Makefile:555: recipe for target 'docs' failed

make: *** [docs] Error 1

The command "make docs" exited with 2.
```
It seems to be Haddock related.

**Comment by b-gehrke** [comment]
All checks pass now. @mcodescu can you just quickly review last 3 commits before we merge this PR?

**Comment by mcodescu** [comment]
Looks good to me. :+1:

**Pull request merged**
