### PR TITLE
fixed #1699

### LINKED ISSUE #1699: provide axiom names for OWL
e.g. using `Annotations: rdfs:label "name"`

### PR DESCRIPTION
**Pull request by tillmo**
needed for speaking axiom names in OWL

### CODE REVIEW

**Comment by tillmo** [comment]
here a DOL ontology for testing:
```
logic OWL

ontology Family1 =
  Class: Person
  Class: Woman SubClassOf: Annotations: rdfs:label "WomanSubClassOfPerson" Person
  ObjectProperty: hasChild
  Class: Mother  
         EquivalentTo: Annotations: rdfs:label "WomanDefinition" Woman and hasChild some Person
  Individual: mary Types: Annotations: rdfs:label "maryIsAWoman" Woman
                   Facts: Annotations: rdfs:label "marysChild" hasChild  john
  Individual: john
  Individual: mary 
       Types: Annotations: Implied "true"^^xsd:boolean, rdfs:label "maryIsAMother"
              Mother
end
```

**Comment by tillmo** [comment]
@mcodescu, @eugenk, can one of you please review this one? @mcodescu, do you have knowledge of the OWL2 logic?

**Comment by mcodescu** [comment]
The code looks fine to me and works :+1:  

I have looked at the OWL2 logic before, so yes, I do have some knowledge. Is there anything to discuss?

**Comment by tillmo** [comment]
no, nothing to dicuss. Then I will merge.

**Pull request merged**
