### PR TITLE
remove majority of warnings

### PR DESCRIPTION
**Pull request by daniilsvc**
Remove majority of warnings appearing during Hets compilation. Warnings about deprecated imports of `network` package will be fixed in #2067. Motivated by https://github.com/spechub/Hets/issues/2065#issuecomment-1178183691. Works both with and without stack.

`Non-exhaustive pattern match` warning in file `Static/PrintDevGraph.hs` was handled by stub `_ -> Doc.empty`. Can be fixed later.

### CODE REVIEW

**Review by mcodescu — COMMENTED** [review]
Looks good. Could this be fixed too?
```

TopHybrid/AS_TopHybrid.hs:2:5: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
2 |   , OverlappingInstances #-}
  |     ^^^^^^^^^^^^^^^^^^^^

ATC/Grothendieck.hs:1:55: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
1 | {-# LANGUAGE UndecidableInstances, FlexibleInstances, OverlappingInstances #-}
```

**Comment by daniilsvc** [comment]
These two files are in `.gitignore`

**Review by mcodescu — APPROVED** [review]
Right. OK to merge then. :+1:

**Comment by daniilsvc** [comment]
Is it OK to change *.der.hs files? They are not in gitignore and I found out that actual .hs files can be changed during compilation.

**Comment by mcodescu** [comment]
Yes, the .der.hs generate the .hs files, it is right to change them.

**Pull request merged**
