### PR TITLE
Write PID file in server mode.

### LINKED ISSUE #1644: Write pidfile in server mode
When Hets starts in server mode, write a file containing the Hets-server's PID. Add an option to specify where this file shall be written.

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1644. It is a dependency of https://github.com/ontohub/ontohub/pull/1689

### CODE REVIEW

**Comment by jelmd** [comment]
Man page should document it as well - see https://github.com/spechub/Hets/blob/master/debian/hets.1

**Comment by eugenk** [comment]
I'm not sure if I added this correctly to the manpage. I've never done it before. Please check.

**Comment by eugenk** [comment]
Is it necessary to delete the pidfile after the application has finished?

**Comment by jelmd** [comment]
Depends on the application. There are a lot of brain damaged apps out there, which just check, whether the pidfile already exists and if so, they pretend they are already running. I.e. they don't even read the file nor check, whether there is a process running with that pid ...
So I would say at least good behavior to rm artifacts.

**Comment by jelmd** [comment]
Just checked:
'\fB\-P\fR \fIfile\fR , \fB\--pidfile=\fIfile\fR' looks better more consistent with the other options (.BR basically means "alternate between Bold and [normal] Roman on each word").

If you wanna check by yourself, use 'tbl ${manfile} | nroff -man -t -Tlp | col -x | less -MRis' or 'groff -Tascii -man -t ${manfile} | less -MRis'.

**Comment by eugenk** [comment]
Both your comments should be done now.

**Comment by tillmo** [comment]
maybe issue a warning if -P is used without -X, otherwise: :+1:

**Comment by eugenk** [comment]
Done with ebc8c6f

**Comment by eugenk** [comment]
@tillmo: is the last change (ebc8c6f) okay?

**Comment by tillmo** [comment]
:+1:

**Pull request merged**
