### PR TITLE
Fixing owl22casl

### PR DESCRIPTION
**Pull request by mcodescu**
Before the datatype translation is fixed, we should merge the concept and sentence translation. A test file is here: https://ontohub.org/sandbox/owl22casl.dol but if I missed something let me know. Also, if you don't like to have all these generated names for variables, I could implement another convention.

### CODE REVIEW

**Comment by tillmo** [comment]
The translation of `max` is not correct. For input
```
logic OWL
spec sp =
  Class: A
  ObjectProperty: r  
  Class: B SubClassOf: r max 2 A
with logic OWL22CASL
end
```
I get
```
forall gn_x1 : Thing
. B(gn_x1)
  => forall gn_x2 : Thing; gn_x3 : Thing; gn_x4 : Thing
     . r(gn_x1, gn_x2) /\ r(gn_x1, gn_x3) /\ r(gn_x1, gn_x4) /\ A(gn_x2)
       /\ A(gn_x3) /\ A(gn_x4)
       => gn_x4 = gn_x2 \/ gn_x4 = gn_x3  
```
But this implies that there is at most 1 such element. Take gn_x2 = gn_x3, then every gn_x4 has to be equal to one of them (and therefore both).

**Comment by tillmo** [comment]
Note that the translation of the same ontology with `exactly` instead of `max` is correct, because there, `not gn_x2 = gn_x3` is assumed.

**Comment by mcodescu** [comment]
This should be: 

```
forall gn_x1 : Thing
. B(gn_x1)
  => forall gn_x2 : Thing; gn_x3 : Thing; gn_x4 : Thing
     . r(gn_x1, gn_x2) /\ r(gn_x1, gn_x3) /\ r(gn_x1, gn_x4) /\ A(gn_x2)
       /\ A(gn_x3) /\ A(gn_x4)
       => gn_x4 = gn_x2 \/ gn_x4 = gn_x3 \/ gn_x2 = gn_x3 
```
namely, if the property holds for more than 2 elements, then at least two of them are equal. Am I right?

**Comment by tillmo** [comment]
yes, right

**Comment by mcodescu** [comment]
done, see last commit

**Comment by tillmo** [comment]
:+1: modulo travis

**Pull request merged**
