### PR TITLE
2014 install dependencies script

### PR DESCRIPTION
**Pull request by daniilsvc**
Issue #2014

### CODE REVIEW

**Comment by mcodescu** [comment]
I have tried the script and I get:
```
./install_dependencies.sh 
Installing dependencies...
[sudo] password for mcodescu: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libncurses5-dev' instead of 'libncurses-dev'
libgtk2.0-dev is already the newest version (2.24.32-1ubuntu1).
libglade2-dev is already the newest version (1:2.6.4-2).
libcairo2-dev is already the newest version (1.15.10-2ubuntu0.1).
libglib2.0-dev is already the newest version (2.56.4-0ubuntu0.18.04.8).
libncurses5-dev is already the newest version (6.1-1ubuntu1.18.04).
libpango1.0-dev is already the newest version (1.40.14-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package postgresql-server-dev-9.5
E: Couldn't find any package by glob 'postgresql-server-dev-9.5'
E: Couldn't find any package by regex 'postgresql-server-dev-9.5'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ant is already the newest version (1.10.5-3~18.04).
```
Is the Postgres9.5 error related to my old Ubuntu version?

Also there's a problem with `make install-owl-tools`:
```
Buildfile: /home/mcodescu/repos/Hets2/OWL2/java/build.xml

Java version in use is 11.0.7 but should be 1.7.x!
Either adjust the 'target-vm' property in the build.xml or use a compatible JVM.
		
Extracting/removing JNI libs from factplusplus*.jar ...

install -m 0755 -d \
	/usr/lib/hets/hets-owl-tools/lib/native/i686 \
	/usr/lib/hets/hets-owl-tools/lib/native/x86_64 \
	/usr/lib/hets/hets-owl-tools/tests
install -m 0644 OWL2/tests/wine.rdf /usr/lib/hets/hets-owl-tools/tests/
install: cannot remove '/usr/lib/hets/hets-owl-tools/tests/wine.rdf': Permission denied
Makefile:848: recipe for target 'install-owl-tools' failed
make: *** [install-owl-tools] Error 1
```
but perhaps we should rather open a new issue for this.

**Comment by daniilsvc** [comment]
if we add `allow-different-user: true` to stack.yaml and run with sudo: `sudo make install-owl-tools` it works.
Then we have warnings, that some packages may not be found but they come from var.mk and not used here directly.

**Comment by b-gehrke** [comment]
In the last meeting we agreed on calling `make install-owl-tools` with `sudo` is fine. The warnings generated by stack are also fine, because `install-owl-tools` doesn't use stack at all.

**Comment by tillmo** [comment]
I think that we agreed that we should inform the user somehow that the warnings can be ignored.

**Review by mcodescu — APPROVED** [review]
:+1:

**Pull request merged**
