### PR TITLE
[WIP] Create Dockerfile for Hets (Server)

### PR DESCRIPTION
**Pull request by ysengrimm**
See #1867 for more information.

### CODE REVIEW

**Comment by tillmo** [comment]
do you understand why "All checks have failed" is displayed, but when clicking on "Details", there are only green tests?

**Comment by ysengrimm** [comment]
It seems like the [PostgreSQL job](https://travis-ci.org/spechub/Hets/jobs/441298590) timed out after 50 min and failed because of that.

**Comment by ysengrimm** [comment]
https://github.com/spechub/Hets/pull/1853#issuecomment-401931173 might fix that problem.

**Comment by ysengrimm** [comment]
The Dockerfile is working now. 
1. Building the Docker container from the Dockerfile:
```
docker build -t spechub/hets .
```
2. Running the container on port 8000 with the data from the current working directory  in `/data` inside the container:
```
docker run --name hets -v `pwd`:/data -p 8000:8000 -ti spechub/hets
```

**Comment by DerProfessor** [comment]
For using the Docker container see [this wiki entry](https://github.com/spechub/Hets/wiki/How-to-use-the-Hets-Docker-Container)

**Pull request merged**
