### PR TITLE
Remove dependencies: wget, cat, tac, grep/ggrep

### PR DESCRIPTION
**Pull request by eugenk**
This removes wget as a dependency. This now uses the package `http-client` to make HTTP calls. It also adds an option to disable TLS certificate verification.

@jelmd, Please tell me if the wget dependency should stay in the Debian control files.

### CODE REVIEW

**Comment by mcodescu** [comment]
The code looks sound to me.

**Comment by jelmd** [comment]
LGTM (non-haskell part).

BTW: If you wanna cleanup dependencies to `cat` and `tac` as well as using POSIX compatible egrep instead of incompatible `grep -e`, have a look at http://iks.cs.ovgu.de/~elkner/tmp/hets-extdeps.patch ;-)

**Comment by eugenk** [comment]
Good point. I added two commits that do this.

**Comment by eugenk** [comment]
Are there any news on the review? Do I need to change things?

**Comment by tillmo** [comment]
it seems that travis fails because http://ppa.launchpad.net/ is down, see also https://twitter.com/launchpadstatus?lang=en

**Comment by eugenk** [comment]
Fixed with fc894d9.

**Comment by eugenk** [comment]
I needed to rebase on master. There were no conflicts, so the diff is the same as before.

**Comment by tillmo** [comment]
actually, I have enabled a rather lax regime: there is no enforcement that new commits must be approved again. Is this useful?

**Comment by eugenk** [comment]
That's absolutely fine for most cases. I just wanted to make sure that you know what the last push is about.

**Pull request merged**
