### PR TITLE
1941 make haddock work

### LINKED ISSUE #1941: make docs/index.html fails
```
make docs/index.html

Check log.haddock for results ...
haddock -o docs -h -s ../%F  \
            -t 'Hets - the Heterogeneous Tool Set' \
            -p Hets-Haddock-Prologue.txt --optghc=-DTAR_PACKAGE --optghc=-DNO_WGET --optghc=-DUNIX --optghc=-DUNI_PACKAGE --optghc=-DHASKELINE --optghc=-DHEXPAT --optghc=-DSERVER --optghc=-DWARP3 --optghc=-DHAXML --optghc=-DRDFLOGIC --optghc=-DCASLEXTENSIONS --optghc=-DGTKGLADE --optghc=-Wall --optghc=-fwarn-tabs --optghc=-fwarn-unrecognised-pragmas --optghc=-fno-warn-orphans --optghc=-fno-warn-unused-do-bind \
             OMDoc.hs COL.hs CspCASLProver.hs ExtModal.hs Proofs.hs CASL.hs Propositional.hs CMDL.hs Isabelle.hs CoCASL.hs s.hs TopHybrid.hs Hybrid.hs hets.hs CspCASL.hs GUI.hs Comorphisms.hs Logic.hs MMT.hs HasCASL.hs Modal.hs OWL2.hs Syntax.hs Taxonomy.hs Driver.hs ATC.hs Common.hs RelationalScheme.hs SoftFOL.hs Framework.hs Haskell.hs Static.hs CASL_DL.hs \
	>log.haddock 2>&1
Makefile:557: recipe for target 'docs/index.html' failed
make: *** [docs/index.html] Error 1
```

### PR DESCRIPTION
**Pull request by tillmo**
shall fix #1941. Not ready for review yet

### CODE REVIEW

**Comment by mcodescu** [comment]
`make docs/index.html` fails with for me:
```
Makefile:557: recipe for target 'docs/index.html' failed
make: *** [docs/index.html] Error 1
```
Attached the generated log file
[log.haddock.txt](https://github.com/spechub/Hets/files/5314557/log.haddock.txt)

**Comment by tillmo** [comment]
Could you pleas try
```
stack setup
make restack
```
and then `make docs` (I have changed the make target).

**Comment by mcodescu** [comment]
No, still same problem. Attached the errors.
[makeDocs.txt](https://github.com/spechub/Hets/files/5317564/makeDocs.txt)

**Comment by mcodescu** [comment]
Same result after a `make distclean; make`

**Comment by mcodescu** [comment]
Fixed the problem with the error, there was an extra hs file in the Hets folder causing it. Now I get:

```
........ warnings
TPTP/AS.hs:293:94: error: parse error on input ‘-- $ite’
Makefile:557: recipe for target 'docs' failed
make: *** [docs] Error 1

```

**Comment by tillmo** [comment]
Please pull the most recent changes; they should fix this problem.

**Comment by mcodescu** [comment]
I have been using the latest commit already. Are you sure everything is checked in? 

Anyways, I fixed the errors by hand and now `make docs` works as expected.

**Comment by tillmo** [comment]
Aha, I have changed `TPTP/AS.hs`, but the right place to change it `TPTP/AS.der.hs`. Have corrected that now.

**Comment by mcodescu** [comment]
There are still errors in TPTP/AS.der.hs:
```
TPTP/AS.hs:1017:27: error:
    parse error on input ‘-- $oType/$o is the Boolean type, i.e., the type of $true and $false.’
Makefile:557: recipe for target 'docs' failed
make: *** [docs] Error 1
```
You should also correct this:
```
data Defined_type = OType -- $oType/$o is the Boolean type, i.e., the type of $true and $false.
                  | O     -- $oType/$o is the Boolean type, i.e., the type of $true and $false.
                  | IType -- $iType/$i is non-empty type of individuals, which may be finite or infinite.
                  | I     -- $iType/$i is non-empty type of individuals, which may be finite or infinite.
                  | TType -- $tType is the type (kind) of all types.
                  | Real  -- $real is the type of <real>s.
                  | Rat   -- $rat is the type of <rational>s.
                  | Int   -- $int is the type of <signed_integer>s and <unsigned_integer>s.
                    deriving (Show, Ord, Eq, Data, Typeable)

```

**Comment by tillmo** [comment]
right, have fixed that

**Comment by mcodescu** [comment]
TPTP/AS.der.hs line 824: "-- | " to "--  |"

Then I get the expected documentation.

**Comment by tillmo** [comment]
OK, fixed

**Review by mcodescu — APPROVED** [review]
:+1: 
Perhaps add something about make docs on hets.eu

**Pull request merged**
