### PR TITLE
added missing dependency

### PR DESCRIPTION
**Pull request by cmaeder**
for calling `cabal build` in the top-level-directory

### CODE REVIEW

**Comment by tillmo** [comment]
With `cabal build`, I get the following problem:
```
till@mark:~/projects/Hets$ cabal configure
Resolving dependencies...
Configuring Hets-0.99...
till@mark:~/projects/Hets$ cabal build
Building Hets-0.99...
Preprocessing executable 'hets' for Hets-0.99...

Haskell/HatAna.hs:19:8:
    Could not find module `Haskell.PreludeString'
    Use -v to see a list of the files searched for.
till@mark:~/projects/Hets$ cabal build -v
creating dist/build
creating dist/build/autogen
Building Hets-0.99...
Preprocessing executable 'hets' for Hets-0.99...
Building executable hets...
creating dist/build/hets
creating dist/build/hets/hets-tmp
/usr/bin/ghc --make -fbuilding-cabal-package -O -odir dist/build/hets/hets-tmp -hidir dist/build/hets/hets-tmp -stubdir dist/build/hets/hets-tmp -i -idist/build/hets/hets-tmp -i. -idist/build/autogen -Idist/build/autogen -Idist/build/hets/hets-tmp -optP-DUNI_PACKAGE -optP-DPROGRAMATICA -optP-DTAR_PACKAGE -optP-DUNIX -optP-DHASKELINE -optP-DHEXPAT -optP-DGTKGLADE -optP-DSERVER -optP-DWARP3 -optP-DCASLEXTENSIONS -optP-DRDFLOGIC -optP-include -optPdist/build/autogen/cabal_macros.h -hide-all-packages -package-db dist/package.conf.inplace -package-id HTTP-4000.2.8-b031f20ea7063bd37594ec79ccfb306f -package-id array-0.4.0.1-3b78425c10ff2dad7acf7e8c8ae014c3 -package-id aterm-0.1.0.1-d36c1429cb639ed1198efc6bbc115442 -package-id base-4.6.0.1-8aa5d403c45ea59dcd2c39f123e27d57 -package-id bytestring-0.10.0.2-4f93248f75667c2c3321a7a6761b576f -package-id case-insensitive-1.1.0.2-a9cc5f442974fbc90a16d92ae924d579 -package-id containers-0.5.0.0-ab1dae9a94cd3cc84e7b2805636ebfa2 -package-id directory-1.2.0.1-91a788fd88acd7f149f0f10f5f1e23f2 -package-id fgl-5.4.2.4-159de3ef3895c423f9edfbf625c737e9 -package-id filepath-1.3.0.1-b12cbe18566fe1532a1fda4c85e31cbe -package-id ghc-prim-0.3.0.0-d5221a8c8a269b66ab9a07bdc23317dd -package-id glade-0.12.1-b441ebe1ec3ef3e7e1f36b1b83030843 -package-id gtk-0.12.4-b93da7450dfc69cb187cd1527af139e9 -package-id haskeline-0.7.0.3-605bae79a8f13adb80fd401c73428585 -package-id hexpat-0.20.6-d30e421816d7059289386aef7ffd3685 -package-id http-types-0.8.6-1798f15632432390631cd390d466e53e -package-id mtl-2.1.2-94c72af955e94b8d7b2f359dadd0cb62 -package-id network-2.4.1.2-040cee5ece44014a8574cb3f87b1eec4 -package-id old-time-1.1.0.1-2f8ea093d0c7014780a8a5772f948883 -package-id parsec-3.1.3-6c6e21cb4ed4ef9d58fdf442940b152e -package-id pretty-1.1.1.0-66181c695e6a2e173ba2088cf55cc396 -package-id process-1.1.0.2-76e05340eb66705981411022731ca84a -package-id programatica-1.0.0.5-4fec8a51b082397c82c271cc3de8d6ba -package-id random-1.0.1.1-43fdc5da991685d8a0ec8cb553880cf8 -package-id tar-0.4.0.1-907344c1240424224fde7bef0cb096e8 -package-id text-0.11.3.1-e38859e86485c167fa7c9441789e7607 -package-id time-1.4.0.1-10dc4804a19dc0000fab79908f1a9f50 -package-id transformers-0.3.0.0-ff2bb6ac67241ebb987351a3db564af0 -package-id uni-events-2.2.1.0-c36dad9ded46e458143f488f8403fe75 -package-id uni-graphs-2.2.1.0-45e9c778b78a8f39f63f9cd29dab8ebc -package-id uni-htk-2.2.1.1-ce3c47e6c38d9b6a9c33920b0de7b5cc -package-id uni-reactor-2.2.1.0-55dce630263aa9120f8d2c4453e351c5 -package-id uni-uDrawGraph-2.2.0.2-f9b74b38397c106eaeddbb8dd4265709 -package-id uni-util-2.3.0.1-5160d1f2b546f22cc4bf468185cdeb02 -package-id unix-2.6.0.1-f12544f106e651e2866b480a05caac7c -package-id utf8-string-0.3.7-26a8ed8ca48fe809983bde6faca943a9 -package-id wai-3.0.3.0-3791b09c5c1b3175cc7f54590804fa39 -package-id wai-extra-3.0.10-689ec6154c2527bd3618c62c1bea9a40 -package-id warp-3.1.3-d4915442c86753f70380e8a65e0141a0 -package-id xml-1.3.12-2c5e1c6121129e6066aca28d897d0d9d -XHaskell98 ./hets.hs -o dist/build/hets/hets -threaded -fcontext-stack=31

Haskell/HatAna.hs:19:8:
    Could not find module `Haskell.PreludeString'
    Use -v to see a list of the files searched for.
till@mark:~/projects/Hets$ 
```

**Comment by cmaeder** [comment]
the missing module is only generated after `make`

**Comment by cmaeder** [comment]
maybe `programatica` should be omitted from Hets.cabal as programatica does no longer compile for ghc-7.10. (but `glade` is also missing for ghc-7.10.)

**Comment by tillmo** [comment]
good idea

**Comment by tillmo** [comment]
I still get the problem:
```
make
[...]
[767 of 767] Compiling Main             ( hets.hs, hets.o ) [flags changed]
Linking hets ...
till@mark:~/projects/Hets$ cabal build
Building Hets-0.99...
Preprocessing executable 'hets' for Hets-0.99...

Haskell/HatAna.hs:19:8:
    Could not find module `Haskell.PreludeString'
    Use -v to see a list of the files searched for.
till@mark:~/projects/Hets$ 
```

**Comment by cmaeder** [comment]
could you try `cabal clean` first?

**Comment by tillmo** [comment]
does not work:
```
till@mark:~/projects/Hets$ cabal clean
cleaning...
till@mark:~/projects/Hets$ make
ghc-pkg: cannot find package parsec1
rm -f rev.txt
echo 1446458312 >> rev.txt
rm -f Driver/Version.hs
cp Driver/Version.in Driver/Version.hs
echo "  ++ \"0.99, 1446458312\"" >> Driver/Version.hs
chmod 444 Driver/Version.hs
ghc -optl-s -XTemplateHaskell -threaded -rtsopts --make -o hets hets.hs -fcontext-stack=26   -DTAR_PACKAGE  -DUNIX -DUNI_PACKAGE -DHASKELINE -DHEXPAT  -DSERVER -DWARP3 -DHAXML  -DRDFLOGIC -DCASLEXTENSIONS -DGTKGLADE  -Wall -fwarn-tabs -fwarn-unrecognised-pragmas -fno-warn-orphans -fno-warn-unused-do-bind  
[713 of 767] Compiling Driver.Version   ( Driver/Version.hs, Driver/Version.o )
Linking hets ...
till@mark:~/projects/Hets$ cabal build
cabal: Run the 'configure' command first.
till@mark:~/projects/Hets$ cabal configure
Resolving dependencies...
Configuring Hets-0.99...
till@mark:~/projects/Hets$ cabal build
Building Hets-0.99...
Preprocessing executable 'hets' for Hets-0.99...

Haskell/HatAna.hs:19:8:
    Could not find module `Haskell.PreludeString'
    Use -v to see a list of the files searched for.
till@mark:~/projects/Hets$ 
```

**Comment by cmaeder** [comment]
It works for me after my last commit. But `cabal build` never works after `make distclean` since many files need to be generated by `make`.

**Comment by cmaeder** [comment]
And I also compile 767 files without programatica

**Comment by cmaeder** [comment]
I'll merge this (if nobody objects)

**Comment by tillmo** [comment]
agreed

**Comment by cmaeder** [comment]
Could you resolve the missing `Haskell.PreludeString` module problem? Maybe (re-)moving a `programatica` folder caused it?

**Comment by cmaeder** [comment]
It should work without programatica folder

**Comment by tillmo** [comment]
the problem now has vanished - I do not know why. But another problem has occurred:
```
cabal build
[...]
[736 of 764] Compiling PGIP.Server      ( PGIP/Server.hs, dist/build/hets/hets-tmp/PGIP/Server.o )

PGIP/Server.hs:231:18:
    Unexpected semi-colons in conditional:
        if null unknown; then parseRESTful
                                newOpts
                                sessRef
                                pathBits
                                (map fst fs2 ++ map (\ (a, b) -> a ++ "=" ++ b) vs)
                                qr2
                                requestBodyParams
                                meth
                                respond; else queryFail
                                                ("unknown query key(s): " ++ show unknown) respond
    Perhaps you meant to use -XDoAndIfThenElse?
```

**Comment by cmaeder** [comment]
This seems to be the indentation problem fixed in #1537

**Comment by cmaeder** [comment]
What `ghc --version` are you using? So fare I could not reproduce the problem. Maybe something (cabal or some configuration files) request stricter layout.

**Comment by cmaeder** [comment]
```
maeder@lati:~/Hets$ cabal --version
cabal-install version 1.22.3.0
using version 1.22.3.0 of the Cabal library 
maeder@lati:~/Hets$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3
```

**Comment by cmaeder** [comment]
I can reproduce it!

**Comment by tillmo** [comment]
OK, then just for the record:
```
ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
till@mark:~/projects/Hets$ cabal --version
cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library 
```

**Comment by tillmo** [comment]
Note that #1537 has not been merged yet. And I am using branch `missing_dependency` for the experiments.

**Comment by tillmo** [comment]
now it goes through!

**Comment by cmaeder** [comment]
Cabal seems to check for stricter layout (otherwise "make" would complain, too).

**Comment by cmaeder** [comment]
http://kwangyulseo.com/2014/01/13/xdoandifthenelse/ I'm not sure what's better: adding the language extension or changing the indentation as done by @gnn

**Comment by tillmo** [comment]
I think adding the language extension is better. I like the syntax of if, then and else all indented at the same level.

**Pull request merged**
