### PR TITLE
1865 recognition of owl sublanguages

### PR DESCRIPTION
**Pull request by b-gehrke**
Recognition of OWL2 DL.

### CODE REVIEW

**Comment by b-gehrke** [comment]
@mcodescu Please review and check the specified sublogics in the test files, too.

One test is currently failing which is fixed in #2045

**Review by mcodescu — COMMENTED** [review]
The code looks really good. Is the test where I've commented the one that is fixed in 2045?

**Comment by b-gehrke** [comment]
> The code looks really good. Is the test where I've commented the one that is fixed in 2045?

The test failing is `10/test3.omn` which is due to an error in parsing SWRLRules in the ontology.

I don't know why `11/test5.ofn` is not working properly in the GUI, but I'll investigate.

**Comment by b-gehrke** [comment]
Apparently, the UI calls `Static.GTheory.sublogicOfTh` to retrieve the sublogic. More importantly, choosing an appropriate prover also relies on this function.
This function does not consider the ontology as a whole but rather folds over the sublogic of each __individual__ sentence. Therefore, global OWL2 restrictions cannot be discovered.

**Comment by mcodescu** [comment]
I think this needs to be changed. @tillmo, do you agree?

**Comment by b-gehrke** [comment]
Changing this would require a change in sublogic calculation/implementation in all language, wouldn't it?

**Comment by mcodescu** [comment]
Yes, it would.

**Review by mcodescu — APPROVED** [review]
:+1: Yes, this is what I expected to see.

**Pull request merged**
